[package]
name = "entry-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
axum = "0.7.4"
dotenvy = "0.15.7"
env_logger = "0.11.3"
log = "0.4.21"
rand = "0.8.5"
sea-orm = { version = "0.12.15", features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
  "with-time",
  "with-json",
  "with-uuid",
] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_yaml = "0.9.32"
thiserror = "1.0.58"
time = { version = "0.3.34", features = ["serde-human-readable"] }
tokio = { version = "1.36.0", features = ["full"] }
tower = "0.4.13"
uuid = { version = "1.7.0", features = ["v4", "serde"] }

axum-macros = "0.4.1"
tower-http = { version = "0.5.2", features = ["cors"] }
http-body-util = "0.1.1"

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = 'z'    # Optimize for size

[profile.bench]
codegen-units = 1
incremental = true
lto = true
opt-level = 'z'    # Optimize for size
