[workspace]
resolver = "2"
members = ["entry-server", "entry-oauth-client"]
default-members = ["entry-server"]
[workspace.package]
name = "entry-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
anyhow = "1.0.81"
dotenvy = "0.15.7"
env_logger = "0.11.3"
log = "0.4.21"
rand = "0.8.5"
serde = "1.0.197"
serde_json = "1.0.114"
thiserror = "1.0.58"
tokio = "1.36.0"
once_cell = "1.19.0"

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = 'z'    # Optimize for size

[profile.bench]
codegen-units = 1
incremental = true
lto = true
opt-level = 'z'    # Optimize for size
