//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::activations::Entity as Activations;
pub use super::licenses::Entity as Licenses;
pub use super::synchronize::Entity as Synchronize;
pub use super::users::Entity as Users;
