//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "activations")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub license_id: i32,
  pub user_id: Uuid,
  #[sea_orm(column_type = "Text", nullable)]
  pub device_id: Option<String>,
  #[sea_orm(column_type = "Text")]
  pub ip_address: String,
  pub activation_date: TimeDateTimeWithTimeZone,
  pub created_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
